# Generated by Django 5.2 on 2026-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_is_phone_verified_kycmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
