# Generated by Django 5.2 on 2026-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_totp_secret_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
