# Generated by Django 5.2 on 2026-06-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usermodel_mfa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='mfa_enabled',
        ),
    ]
