# Generated by Django 5.2 on 2026-06-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_kycmodel_user_backupcodesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcodesmodel',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
