# Generated by Django 5.2 on 2026-06-29 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_backupcodesmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcodesmodel',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='backupcodesmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to=settings.AUTH_USER_MODEL),
        ),
    ]
