# Generated by Django 5.2 on 2026-06-29 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_backupcodesmodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcodesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to=settings.AUTH_USER_MODEL),
        ),
    ]
