# Generated by Django 5.2 on 2026-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_backupcodesmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcodesmodel',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
