# Generated by Django 5.2 on 2026-06-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_backupcodesmodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupcodesmodel',
            name='chances',
        ),
    ]
