# Generated by Django 5.2 on 2026-06-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_backupcodesmodel_chances'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmodel',
            name='account_type',
            field=models.CharField(choices=[('STANDART', 'Private node'), ('BUSINESS', 'Corporate node')], default='STANDART'),
        ),
        migrations.AddField(
            model_name='kycmodel',
            name='inn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycmodel',
            name='legal_full_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycmodel',
            name='signature_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
