# Generated by Django 5.2 on 2026-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_kycmodel_account_type_kycmodel_inn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycmodel',
            name='legal_full_name',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
