# Generated by Django 5.2 on 2026-06-30 14:08

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_kycmodel_legal_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
